repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/pre-commit/pre-commit
    rev: v1.7.0
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/jdswensen/git-hooks
    rev: v0.1.0
    hooks:
    -   id: pretty-c
    -   id: pretty-shell
    -   id: tab-fixer
    -   id: windows-encoding-fixer
